services:
  app:
    build: .
    healthcheck:
      test: ["CMD-SHELL", "php -v || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - app-data:/var/www/html
    user: www-data
    networks:
      - laravel-network
    restart: unless-stopped
    depends_on:
      - postgres

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=team_pulse
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - laravel-network

  nginx:
    image: nginx:alpine
    volumes:
      - app-data:/var/www/html
      - ./nginx/laravel.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    networks:
      - laravel-network
    depends_on:
      - app

networks:
  laravel-network:
    driver: bridge

volumes:
  postgres-data:
  app-data:
